### ISSUE TITLE
Serial

### ISSUE THREAD

**Issue by mgrcf** [roboticslibrary/rl#1]
It would be good to have the possibility to change the mode for std::open in rl::hal::Serial::open. For example, I need O_NDELAY for my application.

**Comment by rickertm** [comment]
Thank you for your feedback. This possibility will be included in the next release of RL.

**Comment by betsch85** [comment]
Is there an ETA on the next release?

**Comment by rickertm** [comment]
We know that a new release is long overdue and currently aim for one this summer.

**Comment by rickertm** [comment]
Please excuse the long delay, the new version allows to set flags in the constructor of `rl::hal::Serial`.
