### ISSUE TITLE
Black Screen on MacOS Catalina

### ISSUE THREAD

**Issue by gi-diana** [roboticslibrary/rl#16]
I have installed RL via homebrew and when I run the first example
 `/usr/local/bin/rlViewDemo /usr/local/share/rl-0.7.0/examples/rlsg/unimation-puma560_boxes.xml
`
and the other examples too I get only a black windows 
when I try to resize and move the window sometimes I can see something behind the black screen 

<img width="805" alt="Screenshot 2020-03-17 at 11 04 09" src="https://user-images.githubusercontent.com/40144238/76845359-0ab3b800-683f-11ea-9e23-e3813ad306d5.png">

How can I do to get things working ?

**Comment by rickertm** [comment]
This is a known issue in Coin3D's SoQt library when using a HiDPI display such as Apple's Retina displays, see coin3d/soqt#1. In this case, the size of the OpenGL window does not match the window size.

I have tried to solve this in a patch for SoQt (see roboticslibrary/soqt@72c62073656780df44e63395596cf1f6966eb6ed), however this does not seem to fix all related issues, especially when moving a window from HiDPI to non-HiDPI displays. On a device with a single Retina display however, this patch should work.

Could you try to build the SoQt dependency with this patch on your machine and link RL against this to see if it solves your issue?

**Comment by gi-diana** [comment]
I've built the SoQt dependency in the branch with your patch and then rebuilt RoboticsLibrary and now is working flawless, Thank You !
<img width="801" alt="Screenshot 2020-03-18 at 11 12 14" src="https://user-images.githubusercontent.com/40144238/76949734-5337a800-6909-11ea-9d5d-6ee3d9cabbec.png">
