### ISSUE TITLE
[Question] Is there a simple way to visualise a FCL scene?

### ISSUE THREAD

**Issue by BeardedVagabond** [roboticslibrary/rl#32]
I'm looking at implementing octomap collision objects similar to the question raised [in a recent issue](https://github.com/roboticslibrary/rl/issues/21) so it looks like I require an FCL scene. With that, I'd like to be able to visualise things similar to the method explained [in the first steps tutorials](https://www.roboticslibrary.org/tutorials/first-steps-windows/) however those tutorials use so scenes and SoQT. 

I'm very much a beginner with QT so I have no idea where to start with this. I tried looking through the rlPlanDemo source but it is very expansive for someone with little knowledge of QT etc. In my actual implementation, I won't need visualisation of any kind, but it would help a lot in the development process.

**Comment by rickertm** [comment]
I have looked into adding support in `rl::sg::fcl::Shape` to use SoVRMLPointSet nodes for creating `fcl::OcTree` geometries. This way you could use a VRML file to define a list of points that are used for initializing an octree. The resolution would be specified in a corresponding node in the scene XML file. Of course this is only useful for a static point cloud, e.g., in a predefined scenario for rlPlanDemo. A dynamic update would still require handling the updates yourself. The visual scene by default would show the defined points, however the octree boxes could optionally be shown as well.

The optional visualization code for rlPlanDemo, e.g., at the end of `MainWindow::load`, that I used in the issue linked above looks like this:
```cpp
if (rl::sg::fcl::Scene* scene = dynamic_cast<rl::sg::fcl::Scene*>(this->scene.get()))
{
	for (std::size_t i = 0; i < scene->getNumModels(); ++i)
	{
		for (std::size_t j = 0; j < scene->getModel(i)->getNumBodies(); ++j)
		{
			for (std::size_t k = 0; k < scene->getModel(i)->getBody(j)->getNumShapes(); ++k)
			{
				if (rl::sg::fcl::Shape* shape = dynamic_cast<rl::sg::fcl::Shape*>(scene->getModel(i)->getBody(j)->getShape(k)))
				{
					if (const fcl::OcTree<rl::math::Real>* octree = dynamic_cast<const fcl::OcTree<rl::math::Real>*>(shape->getCollisionObject()->collisionGeometry().get()))
					{
						std::vector<std::array<rl::math::Real, 6>> boxes = octree->toBoxes();
						
						SoVRMLTransform* vrmlRoot = new SoVRMLTransform();
						
						rl::math::Transform frame;
						scene->getModel(i)->getBody(j)->getFrame(frame);
						rl::math::Transform transform;
						shape->getTransform(transform);
						
						rl::math::Transform frameTransform = frame * transform;
						
						SbMatrix matrix;
						
						for (int m = 0; m < 4; ++m)
						{
							for (int n = 0; n < 4; ++n)
							{
								matrix[m][n] = static_cast<float>(frameTransform(n, m));
							}
						}
						
						vrmlRoot->setMatrix(matrix);
						
						for (std::size_t l = 0; l < boxes.size(); ++l)
						{
							SoVRMLShape* vrmlShape = new SoVRMLShape();
							SoVRMLBox* vrmlBox = new SoVRMLBox();
							vrmlBox->size.setValue(boxes[l][3], boxes[l][3], boxes[l][3]);
							vrmlShape->geometry = vrmlBox;
							SoVRMLMaterial* vrmlMaterial = new SoVRMLMaterial();
							vrmlMaterial->diffuseColor.setValue(1.0 - boxes[l][4], 1.0 - boxes[l][4], 1.0 - boxes[l][4]);
							vrmlMaterial->emissiveColor.setValue(1.0 - boxes[l][4], 1.0 - boxes[l][4], 1.0 - boxes[l][4]);
							SoVRMLAppearance* vrmlAppearance = new SoVRMLAppearance();
							vrmlAppearance->material = vrmlMaterial;
							vrmlShape->appearance = vrmlAppearance;
							SoVRMLTransform* vrmlTransform = new SoVRMLTransform();
							vrmlTransform->translation.setValue(boxes[l][0], boxes[l][1], boxes[l][2]);
							vrmlTransform->addChild(vrmlShape);
							vrmlRoot->addChild(vrmlTransform);
						}
						
						this->scene2->root->addChild(vrmlRoot);
					}
				}
			}
		}
	}
}
```
