### ISSUE TITLE
CGAL problem

### ISSUE THREAD

**Issue by OgreTransporter** [roboticslibrary/rl#4]
Hi,

I try to follow the tutorial on http://www.roboticslibrary.org/tutorials/build-windows. But I'm not able to build RL, because RL has some problems with CGAL in src/rl/plan/Orthogonal_k_neighbor_search.h. I've downloaded the latest stable version (4.7).

**Comment by rickertm** [comment]
Hello,
please use CGAL version 4.5.2 with the current version of RL. The k-d tree changes introduced in CGAL 4.6 are not compatible with our modifications in Orthogonal_k_neighbor_search.h for rotational joints with no limits.

**Comment by rickertm** [comment]
Please excuse the long delay, the new version does not require CGAL any longer.
