### ISSUE TITLE
Source doesn't compile our of the box.

### ISSUE THREAD

**Issue by jettan** [roboticslibrary/rl#6]
If I try to compile this library, it will crash because of the following line (-fpermissive).

https://github.com/roboticslibrary/rl/blob/master/src/rl/math/TransformAddons.h#L128
Removing the ```return res;```  statement fixes the problem.

**Comment by rickertm** [comment]
Thank you for pointing out this issue. Commit 58d12d1efdfb384dee504f31087f4b47ab7bbc93 should fix this.
