### ISSUE TITLE
How can I check if the trajectory remains valid while the robot moves?

### ISSUE THREAD

**Issue by RodrigoCodeBernardo** [roboticslibrary/rl#65]
How can I check if my generated trajectory is valid along the robot motion? 

The goal is to change the robot's surroundings, and if an obstacle appears on the initially calculated path, it will send an alert.

There is a way to check the path through one of the functions: RecursiveVerifier or Verifier.

As inputs would have a different scenario than the one in which the plan was constructed, the robot's kinematics and the path initially obtained.

Thanks

**Comment by RodrigoCodeBernardo** [comment]
There is a way to check the path through one of the functions: RecursiveVerifier or Verifier.

As inputs would have a different scenario than the one in which the plan was constructed, the robot's kinematics and the path initially obtained.

**Comment by RodrigoCodeBernardo** [comment]
Hi

I found this solution, which works for now. What I do is import a new scenario and check for each point of the trajectory if it still remains feasible. There may be a better solution I am open to suggestions.

`		rl::plan::SimpleModel simpleModel;
		rl::math::Vector pose(6);	
		bool isColliding;

		simpleModel.mdl = kinematic.get(); // for rl::mdl::Kinematic*
		simpleModel.scene = &scene2;
		simpleModel.model = scene2.getModel(0); // id of kinematic model in scene
		
		optimizer.process(path_optimised);
		
		for (rl::plan::VectorList::iterator e = path_optimised.begin(); e != path_optimised.end(); ++e)
		{	
			pose = e->transpose();
			isColliding = simpleModel.isColliding(pose);
			std::cout << "isColliding() " << (isColliding ? "true" : "false") << std::endl;
		}`

**Comment by rickertm** [comment]
The verifiers internally call `rl::plan::SimpleModel::isColliding`, so your approach should work for that use case. `rl::plan::SimpleModel` combines the kinematic & geometric models and filters tests of `rl::sg::SimpleScene::areColliding` between bodies based on the robot's collision definitions.
