### ISSUE TITLE
Black Screen on Ubuntu22.04 and unable to see normally

### ISSUE THREAD

**Issue by jack416** [roboticslibrary/rl#90]
Use in VM(VMware® Workstation 17 Pro) ubuntu22.04 gcc/g++ version 11.4.0  cmake version 3.22.1

I have installed RL via homebrew and when I run the first example

and the other examples too I get only a black windows 

but save as png have rendered content ,both the master and 0.7 branch has this problem， like this

run：
/usr/local/bin/rlPlanDemo /usr/local/share/rl-0.7.0/examples/rlplan/unimation-puma560_boxes_rrtConCon.xml

running results：
![image](https://github.com/roboticslibrary/rl/assets/8808197/77faa326-3ed5-43b2-b262-66e3c374cbfa)

I'm a beginner in RL ,How can I do to get things working ?

**Comment by MarceloEO** [comment]
Hi Jack,
Try to change the render buffer type to single:

right button on the rendering scene -> draw styles -> Render buffer type -> Single 

I hope this will help you!

**Comment by jack416** [comment]
> Hi Jack, Try to change the render buffer type to single:
> 
> right button on the rendering scene -> draw styles -> Render buffer type -> Single
> 
> I hope this will help you!

Thank you for your response. I have implemented the above functionality using thefunction.
Thanks！
