### ISSUE TITLE
How to implement MoveL and MoveC?

### ISSUE THREAD

**Issue by xianjimli** [roboticslibrary/rl#91]
I would like the end-effector of the robotic arm to move in straight lines and arcs instead of the shortest path. Could you give me an implementation idea? Thank you.

**Comment by rickertm** [comment]
For implementing linear and circular trajectories in operational space, you need to define trajectories for the position and orientation of the end effector in operational space. These can be combined into a 6D position+orientation vector and transformed to the robot's configuration space via the inverse of the Jacobian matrix.

The classes rl::math::Polynomial and rl::math::Spline include a few functions for interpolation position vectors, they also include a specialization for quaternions that can be used for the orientations. rl::math::Circular3 can be used to interpolate a circular segment through three points.

**Comment by xianjimli** [comment]
Thank you so much
