### ISSUE TITLE
Robotics Library Debug Version

### ISSUE THREAD

**Issue by philchenup** [roboticslibrary/rl#93]
First of all, thank you very much to the blogger for releasing the Robotics Library; it has been very beneficial to me. However, currently, only the Release version of the library is available. Could you let me know where I can download the Debug version of the library or provide instructions on how to compile the Debug version? Thank you very much.

**Comment by rickertm** [comment]
The website includes tutorials on how to build RL from source on various platforms, e.g., [Windows with MSVC](https://www.roboticslibrary.org/tutorials/build-windows/). The latest version is also built in a CI workflow in Release mode and the artifacts are available on GitHub. The Debug build for the latest version however is not included and has to be built separately.

For the third-party dependencies there is an extra repository [roboticslibrary/rl-3rdparty](https://github.com/roboticslibrary/rl-3rdparty) that builds these in a CI workflow for MSVC in Debug and Release mode. On other platforms these should be available via the package manager, on Windows vcpkg also includes support for most of them.
